### ISSUE TITLE
Add RPM spec file

### ISSUE THREAD

**Issue by SpareSimian** [dfskoll/mailmunge#1]
I'd like to install this on CentOS 7 and Rocky 8, alongside my existing MIMEDefang RPM during migration and testing. I want to keep all the apps I install tracked by the package system for easy maintenance, so a SPEC file to build an RPM would be welcome.

**Comment by dfskoll** [comment]
I don't have easy access to any RPM-based systems... PR would be welcomed.

**Comment by SpareSimian** [comment]
I knocked together a candidate but have a few issues getting files installed to the BUILDROOT in the correct places for a package. I don't know if there are arguments to configure or make install to do this or if I need to reshuffle things after make install runs.

systemd files should go in /usr/lib/systemd/system instead of /etc/systemd/system.
/etc/init.d/mailmunge would duplicate the systemd service so I want to suppress its installation. (But I can remove it in the %install section.)
Use /usr instead of /usr/local for perl files.
[mailmunge-v3.07-1.spec.txt](https://github.com/dfskoll/mailmunge/files/8783399/mailmunge-v3.07-1.spec.txt)

I think /etcdefault/mailmunge.example belongs in %doc, to be copied/renamed by the user to /etc/default.

**Comment by dfskoll** [comment]
This is a good start, but I think it can use a bit of improvement.  I'll address your points:

- systemd files should go in /usr/lib/systemd/system instead of /etc/systemd/system: This can be done by moving them after the `make install` step.
- `/etc/init.d/mailmunge` likewise can be removed after `make install`
- Invoke `./configure` as `./configure --prefix=/usr` to put everything in the right place, including the Perl files that will go into the system Perl directories.
- I'm not sure about `/etc/default/mailmunge.example`.  I like it in `/etc/` but it can always be moved to `%doc` if that's preferable.

The two big things that need fixing IMO are:

1. I don't think we should make one monolithic package.  If you look under `debian/` you'll see that I build 10 packages that install the files in _packagename_`.install`  Someone might legitimately want to install Mailmunge without wanting to use SpamAssassin or some of the actions like adding boilerplate text; I think the RPM packages should reflect the Debian ones.
2. This leads to the second point: The packages should have dependency information.  The Debian dependencies are in `debian/control` and the RPM dependencies should mirror those (with correct package names, of course, where they are named differently in the RPM ecosystem.)

I don't have a ton of time in the next few days to work on this, but I can take a crack at it next week unless you'd like to do so first.

Regards,

Dianne.

**Comment by SpareSimian** [comment]
Thanks, that helps a lot. I can go ahead and update it based on your guidance.

I saw that the MIMEDefang spec file splits into lots of subpackages but didn't know what would be appropriate for Mailmunge so it's good to hear you have that worked out for Debian. I'll look at its packaging control files in more detail to see how that works.

I'd intended to flesh out dependencies but left that for a second pass. I did see a lot of _build_ dependencies in the RHEL build instructions (long dnf install command) but I found I only needed the few in my initial spec file to get the build step to complete. dnf pulled in a long list of other Perl modules with those few. I'm only concerned now that configure might have left out functions due to missing dependencies. I'll pay closer attention to the configure output to see if I need to add back some dependencies to re-enable any missing features.

**Comment by dfskoll** [comment]
Cool, thank you!  And I've installed a Rocky 8 LXC container so I can meaningfully assist you with this.  I appreciate your willingness to help.

**Comment by SpareSimian** [comment]
I wasn't familiar with /etc/default and learned that it's the Debian equivalent of Red Hat's /etc/sysconfig:

https://www.reddit.com/r/linux/comments/isp0x/on_etcsysconfig_and_etcdefault/

So I think the RPM should install the file to /etc/sysconfig without the .example suffix (since it's all comments).

**Comment by dfskoll** [comment]
> So I think the RPM should install the file to /etc/sysconfig without the .example suffix (since it's all comments).

That's fine, as long as RPM-based distros are smart enough not to overwrite it on upgrade.  I also had to make the systemd units look in `/etc/sysconfig` for environment variables, which is done in https://github.com/dfskoll/mailmunge/commit/de2054c0180e72b0fafb8f6bc5f3ce09a6781fb1

Regards,

Dianne.

**Comment by SpareSimian** [comment]
Here's a snapshot of work in progress. This shuffles the files to their desired locations. It doesn't yet include subpackages. 

I'm getting a packaging error about missing debuginfo but I see the build compiling with -g so I don't know what that's about. 

`
error: Empty %files file /home/buildmeister/rpmbuild/BUILD/mailmunge-3.07/debugsourcefiles.list
`

[mailmunge-v3.07-2.spec.txt](https://github.com/dfskoll/mailmunge/files/8792417/mailmunge-v3.07-2.spec.txt)

**Comment by dfskoll** [comment]
I believe this issue is now closed in 3.08-BETA-1
